// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE7rfeqG6l1dVr7-HtsTzt0a66vDEQn7c',
    appId: '1:87902432541:web:26afd37e55ff85179b85f4',
    messagingSenderId: '87902432541',
    projectId: 'my-application222-4fe42',
    authDomain: 'my-application222-4fe42.firebaseapp.com',
    storageBucket: 'my-application222-4fe42.firebasestorage.app',
    measurementId: 'G-BNSW0G4FP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDinXmxbVK4KEeJFABKE09_7WJVpMlt1oY',
    appId: '1:87902432541:android:9f2d24bf570a24969b85f4',
    messagingSenderId: '87902432541',
    projectId: 'my-application222-4fe42',
    storageBucket: 'my-application222-4fe42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXVLlBOIF6neTIMHbt3FJJVAzxkjzXq7s',
    appId: '1:87902432541:ios:b2871d3b71ded07a9b85f4',
    messagingSenderId: '87902432541',
    projectId: 'my-application222-4fe42',
    storageBucket: 'my-application222-4fe42.firebasestorage.app',
    iosBundleId: 'com.example.desaWisata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXVLlBOIF6neTIMHbt3FJJVAzxkjzXq7s',
    appId: '1:87902432541:ios:b2871d3b71ded07a9b85f4',
    messagingSenderId: '87902432541',
    projectId: 'my-application222-4fe42',
    storageBucket: 'my-application222-4fe42.firebasestorage.app',
    iosBundleId: 'com.example.desaWisata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE7rfeqG6l1dVr7-HtsTzt0a66vDEQn7c',
    appId: '1:87902432541:web:394e0dfa7c4bc8119b85f4',
    messagingSenderId: '87902432541',
    projectId: 'my-application222-4fe42',
    authDomain: 'my-application222-4fe42.firebaseapp.com',
    storageBucket: 'my-application222-4fe42.firebasestorage.app',
    measurementId: 'G-GBQHTJLK21',
  );
}

/// Check if Firebase options are still using placeholder values.
bool get isFirebaseOptionsPlaceholder {
  return DefaultFirebaseOptions.currentPlatform.apiKey.contains('REPLACE') ||
      DefaultFirebaseOptions.currentPlatform.projectId.contains('REPLACE');
}
